### ISSUE TITLE
ViM-UNet: Vision Mamba for Biomedical Segmentation

### ISSUE THREAD

**Issue by anwai98** [radarFudan/Awesome-state-space-models#1]
Hi @radarFudan,

We have our recent contribution accepted at MIDL 2024, I'll leave the relevant links below:

Preprint: https://doi.org/10.48550/arXiv.2404.07705
Code: https://github.com/constantinpape/torch-em/blob/main/vimunet.md
MIDL 2024 Paper: https://openreview.net/forum?id=PYNwysgFeP

Thanks for maintaining this awesome repo! :)

**Comment by radarFudan** [comment]
I have updated the paper list with your work~
