### ISSUE TITLE
Adding Longhorn

### ISSUE THREAD

**Issue by Cranial-XIX** [radarFudan/Awesome-state-space-models#6]
Hi, thanks for this awesome repo! Just want to bring up another related work in state space models: 

LONGHORN: STATE SPACE MODELS ARE AMORTIZED ONLINE LEARNERS (https://arxiv.org/pdf/2407.14207), which is under submission to ICLR 2025.

We show that the design of SSM can be reduced to design the online learning objectives, and propose to use the implicit online learning closed-form update as the SSM's recurrence, which demonstrates superior performance to Mamba despite it has slightly fewer parameters.

**Comment by radarFudan** [comment]
Updated.
